### ISSUE TITLE
Cant add new book to the DB

### ISSUE THREAD

**Issue by ishayrabi** [nirgn975/Book4You#79]
when I try to add a new book the submit button is disabled even after inserting all the columns properly.

**Comment by nirgn975** [comment]
@ishayrabi yep because of the image, I try to convert it, but I'll remove the validation on the image for now.
I'll do it tomorrow and you should do `git pull` after it (I think it's called `sync` on the GitHub software).

**Comment by ishayrabi** [comment]
Alright, thanks @nirgn975 .

**Comment by nirgn975** [comment]
Fix that on #75 - Close this issue.
